name: Deploy to Prod
on:
    workflow_run:
      branches:
        - 'main'
    workflow_dispatch:
      inputs:
        version:
          description: 'Setup app version ex. 1.x'
          required: true
          type: string

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag netflyer/helloworld:${{ input.version }} --tag  netflyer/helloworld:latest
    - name: Push image to 
      run: docker push netflyer/helloworld:${{ input.version }} && docker push netflyer/helloworld:latest

    - name: Check out CD repo
      uses: actions/checkout@v3
      with:
        repository: alekseydemidov/testargo-cd
        ref: prod
        token: ${{ secrets.TESTARGO_CD_TOKEN }}

    - name: Change tag for application
      run: |
        git config --global user.email "testargo@example.com"
        git config --global user.name "Test Argo"
        sed -i -e "s/tag: .*/tag: ${{ input.version }}/"  ./helm/values.yaml
        cat ./helm/values.yaml
        git add ./helm/values.yaml
        git commit -m "New app version ${{ input.version }}" 
        git push
        