name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag netflyer/helloworld:${{ github.run_number }} && docker tag netflyer/helloworld:${{ github.run_number }} netflyer/helloworld:latest
    - name: Push image to 
      run: docker push netflyer/helloworld:${{ github.run_number }} && docker push netflyer/helloworld:latest
